-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_mailutils_message_party`;
DROP TABLE IF EXISTS `civicrm_mailutils_message`;
DROP TABLE IF EXISTS `civicrm_mailutils_setting`;
DROP TABLE IF EXISTS `civicrm_mailutils_template`;
DROP TABLE IF EXISTS `civicrm_mailutils_thread`;

SET FOREIGN_KEY_CHECKS=1;